# Generated by Django 5.0.6 on 2024-06-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_notification_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='censored_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
