# Generated by Django 5.0.6 on 2024-06-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blurred_image',
            field=models.ImageField(blank=True, null=True, upload_to='blurred_images/'),
        ),
    ]
